---
# tasks file for gitlab-ee

- name: include default variables
  include_vars: "../vars/main.yml"

- name: apt-key add
  apt_key:
    keyring: "{{ item.keyring }}"
    url: "{{ item.url }}"
    id: "{{ item.id }}"
    state: "{{ item.state }}"
  loop: "{{ _apt_key }}"
  register: result
  until: result is succeeded

- name: apt-add-repository
  apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ _apt_repository }}"
  register: result
  until: result is succeeded

- name: apt-mark unhold
  dpkg_selections:
    name: "{{ item.name | regex_replace('^(.*)=[0-9]*:*[0-9]+\\..*$', '\\1') }}"
    selection: "install"
  loop: "{{ _apt }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _apt }}"
  register: result
  until: result is succeeded
  notify:
    - gitlab_ee | gitlab-ctl reconfigure
    - gitlab_ee | systemctl restart gitlab-runsvdir.service

- name: apt-mark hold
  dpkg_selections:
    name: "{{ item.name | regex_replace('^(.*)=[0-9]*:*[0-9]+\\..*$', '\\1') }}"
    selection: "hold"
  loop: "{{ _apt }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false

- name: groupadd
  group:
    name: "{{ item.name }}"
    system: true
    state: "present"
  loop:
    - { name: "gitlab-www" }
    - { name: "git" }
    - { name: "gitlab-redis" }
    - { name: "gitlab-psql" }
    - { name: "mattermost" }
    - { name: "registry" }
    - { name: "gitlab-prometheus" }
    - { name: "gitlab-consul" }

- name: useradd
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    password: "{{ item.password | default(omit) }}"
    system: true
    create_home: false
    state: "present"
  loop:
    - { name: "gitlab-www", group: "gitlab-www", home: "/var/opt/gitlab/nginx", shell: "/bin/false" }
    - { name: "git", group: "git", home: "/var/opt/gitlab", shell: "/bin/sh", password: "*" }
    - { name: "gitlab-redis", group: "gitlab-redis", home: "/var/opt/gitlab/redis", shell: "/bin/false" }
    - { name: "gitlab-psql", group: "gitlab-psql", home: "/var/opt/gitlab/postgresql", shell: "/bin/sh" }
    - { name: "mattermost", group: "mattermost", home: "/var/opt/gitlab/mattermost", shell: "/bin/sh" }
    - { name: "registry", group: "registry", home: "/var/opt/gitlab/registry", shell: "/bin/sh" }
    - { name: "gitlab-prometheus", group: "gitlab-prometheus", home: "/var/opt/gitlab/prometheus", shell: "/bin/sh" }
    - { name: "gitlab-consul", group: "gitlab-consul", home: "/var/opt/gitlab/consul", shell: "/bin/sh" }

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/etc/gitlab", mode: "0775" }
    - { dest: "/var/log/gitlab" }
    - { dest: "/var/opt/gitlab" }
    - { dest: "/var/opt/gitlab/consul", owner: "gitlab-consul", group: "gitlab-consul" }
    - { dest: "/var/opt/gitlab/mattermost", owner: "mattermost", group: "mattermost" }
    - { dest: "/var/opt/gitlab/nginx", owner: "root", group: "gitlab-www", mode: "0750" }
    - { dest: "/var/opt/gitlab/postgresql", owner: "gitlab-psql", group: "gitlab-psql" }
    - { dest: "/var/opt/gitlab/prometheus", owner: "gitlab-prometheus", group: "gitlab-prometheus", mode: "0750" }
    - { dest: "/var/opt/gitlab/redis", owner: "gitlab-redis", group: "git", mode: "0750" }
    - { dest: "/var/opt/gitlab/registry", owner: "registry", group: "registry" }



- name: copy templates
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: "/etc/gitlab/gitlab.rb" }
  notify:
    - gitlab_ee | gitlab-ctl reconfigure
    - gitlab_ee | systemctl restart gitlab-runsvdir.service

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/etc/gitlab/gitlab.rb" }
  notify:
    - gitlab_ee | gitlab-ctl reconfigure
    - gitlab_ee | systemctl restart gitlab-runsvdir.service

- name: flush handlers
  meta: flush_handlers

- name: systemctl start gitlab-runsvdir.service
  service:
    name: "gitlab-runsvdir.service"
    state: "started"
    enabled: true
  changed_when: false
  failed_when: false