---
# vars file for gitlab-ee
_gitlab_version:
  "14.4": 14.4.2-ee

_apt_key:
  - keyring: "/etc/apt/trusted.gpg.d/gitlab-ee.gpg"
    url: "http://packages.gitlab.com/gitlab/gitlab-ee/gpgkey"
    id: "F6403F6544A38863DAA0B6E03F01618A51312F3F"
    state: "present"

_apt_repository:
  - filename: "gitlab-ee"
    repo: "deb http://packages.gitlab.com/gitlab/gitlab-ee/ubuntu focal main"
    state: "present"

_apt:
  - { state: "latest", name: "ca-certificates" }
  - { state: "latest", name: "curl" }
  - { state: "latest", name: "gitlab-cli" }
  - { state: "latest", name: "libssl1.1" }
  - { state: "latest", name: "openssl" }
  - { state: "latest", name: "python3-gitlab" }
#  - { state: "latest", name: "gitlab-ee" }
  - { state: "present", name: "gitlab-ee={{ gitlab_version }}*" }